### ISSUE TITLE
Where should I write registers?

### ISSUE THREAD

**Issue by libook** [jiangtj/hexo-extend-injector2#20]
I have installed this plugin. So where should I write registers? I mean which file should I write register code in?

**Comment by libook** [comment]
Okay, it seems that Hexo have in-build rejector.
https://hexo.io/api/injector
Is that your work? Nice work anyway.

**Comment by jiangtj** [comment]
> Is that your work?

No, It's code by sukka. In fact, in-build rejector doesn't fit my [theme ](https://github.com/jiangtj/hexo-theme-cake) needs, so I wrote a more versatile Injector.

> I have installed this plugin. So where should I write registers? I mean which file should I write register code in?

In the js file of any theme or plugin
